### ISSUE TITLE
Rimuovere PCA da opzioni

### ISSUE THREAD

**Issue by TotallyLuke** [QuaranTeam2021/HD-Viz#12]
Crea conflitti

**Comment by MatteoSinigaglia** [comment]
In che senso? Eliminarlo come algoritmo?

**Comment by TotallyLuke** [comment]
Sì, l'ho anche eliminato dai casi d'Uso. La MALP utilizza già una versione (modificata) di PCA per individuare ascissa è ordinata dei punti. Non vorrei venissero poste domande come "Ma se plotto con MALP dati già ridotti con PCA...". E poi Piccoli ha detto che la riduzione con PCA lascia a desiderare.

**Comment by Dam-99** [comment]
Rimuovere completamente o solo per MALP?

**Comment by TotallyLuke** [comment]
Completamente. Guarda l'indice di AdR, puf, è scomparsa la riduzione con PCA

**Comment by Dam-99** [comment]
Sei magico allora
