### ISSUE TITLE
Nome file caricamento db

### ISSUE THREAD

**Issue by MatteoSinigaglia** [QuaranTeam2021/HD-Viz#15]
Il nome della tabella non deve contenere l'estensione, ex .csv

**Comment by Dam-99** [comment]
@MatteoSinigaglia sarebbe un problema se il nome fosse `nome_file.csv.json` e solo l'ultima parte venisse rimossa?

**Comment by QuaranTeam2021** [comment]
Non è carino salvare sul db .csv etc, però se il db lo permette sti cazzi

**Comment by Dam-99** [comment]
Boh io nel dubbio faccio che tolga tutto, in caso basta aggiungere un `$` nella regexp
