### ISSUE TITLE
Messaggio attesa calcolo grafico

### ISSUE THREAD

**Issue by TotallyLuke** [QuaranTeam2021/HD-Viz#19]

**Comment by Dam-99** [comment]
In pausa perché i metodi che avevo provato non hanno funzionato (l'interfaccia si blocca ugualmente) e non mi viene in mente nient'altro
Testati:
- web worker: gli oggetti della nostra architettura non sono trasferibili tra i worker come un messaggio, servirebbe ripensare tutto in modo che si possa sfruttare il modello ad attori (in teoria)
- icona caricamento inserita prima di avviare la creazione: per qualche motivo il render con l'icona di caricamento non avveniva prima di avviare la creazione del grafico
Soluzione temporanea: messaggio a fianco del bottone conferma
