### ISSUE TITLE
Stringhe

### ISSUE THREAD

**Issue by QuaranTeam2021** [QuaranTeam2021/HD-Viz#3]
Tutti gli algoritmi con le stringhe crepano! 
- Introdurre un pre-passaggio per chiedere all'utente quali colonne sono numeriche
- Aggiungere colonne numeriche allo Store

**Comment by TotallyLuke** [comment]
Assumendo che ciascuna colonna contiene dati tutti dello stesso tipo e che un dataset contiene almeno una riga di intestazioni e una di dati si potrebbe verificare se `typeof data[1][d] === "number"` per ogni colonna `d`

**Comment by QuaranTeam2021** [comment]
Se siamo certi che tutte le colonne hanno lo stesso tipo di dati si
