### ISSUE TITLE
Parsing con ultima riga vuota

### ISSUE THREAD

**Issue by TotallyLuke** [QuaranTeam2021/HD-Viz#37]
A quanto pare produce valori nulli (puntini fuori dal grafico) e fa crashare linearProjection. C'è un modo semplice di rimuovere le righe vuote o lasciamo così?

https://user-images.githubusercontent.com/74210939/119539425-74591b80-bd8c-11eb-8319-c3189e872c16.mp4

**Comment by TotallyLuke** [comment]
Propongo (non so in che branch farlo) di aggiungere una riga che a quanto pare risolve il problema (1 esempio testato):![Screenshot from 2021-05-25 22-54-41](https://user-images.githubusercontent.com/74210939/119567222-58657200-bdac-11eb-9631-9a1e78ff4aea.png)
@MatteoSinigaglia @federicochiarello

**Comment by QuaranTeam2021** [comment]
Va bene, fallo pure in controller
