### ISSUE TITLE
Avviso Caricamento lento non deve resettare pagina

### ISSUE THREAD

**Issue by TotallyLuke** [QuaranTeam2021/HD-Viz#47]
@federicochiarello sa

**Comment by federicochiarello** [comment]
Se è riferito al fatto che cliccando sull'avviso si resetta la pagina, penso che ci abbia pensato @fedeconsa

**Comment by fedeconsa** [comment]
Il problema è che c'è il link "visualization" che porta al grafico e che nonostante sia disabilitato se ci clicchi ti indirizza comunque, intanto l'ho spostato così che non includa l'avviso del caricamento lento, che adesso non è più un bottone @Dam-99 se puoi guardarci
