### ISSUE TITLE
limite massimo colonne SCPM

### ISSUE THREAD

**Issue by alicegibe** [QuaranTeam2021/HD-Viz#49]

**Comment by TotallyLuke** [comment]
https://user-images.githubusercontent.com/74210939/120537137-3a6bc300-c3e5-11eb-90ca-ff514e59e0cd.mp4

Il limite dovrebbe esistere solo se si seleziona ScptM e nessuna riduzione, altrimenti dovrebbe essere possibile selezionare più colonne
