### ISSUE TITLE
Tooltip FF con undefined

### ISSUE THREAD

**Issue by TotallyLuke** [QuaranTeam2021/HD-Viz#59]
Leggere commento successivo

**Comment by TotallyLuke** [comment]
La causa sembra essere questa:
https://user-images.githubusercontent.com/74210939/121589566-80550680-ca37-11eb-941a-3ba900f77cf9.mp4

Perciò mi tolgo la issue e la prende qualcun altro

**Comment by Dam-99** [comment]
risolto in 1886fbe

**Comment by TotallyLuke** [comment]
Non ho modo di verificare 
![Screenshot from 2021-06-10 22-10-35](https://user-images.githubusercontent.com/74210939/121590568-bf378c00-ca38-11eb-90b4-934a9a46ad9a.png)

**Comment by Dam-99** [comment]
My bad ho caricato per sbaglio una modifica non correlata

**Comment by TotallyLuke** [comment]
Ok.
https://user-images.githubusercontent.com/74210939/121591643-083c1000-ca3a-11eb-82a4-9c1dc77a9d88.mp4
