### ISSUE TITLE
Aggiunta guida dell'applicazione

### ISSUE THREAD

**Issue by TotallyLuke** [QuaranTeam2021/HD-Viz#61]
-afedeconsa

**Comment by Dam-99** [comment]
Inserito funzionamento, manca contenuto
d538cead

**Comment by TotallyLuke** [comment]
- [x] possibilmente non a tutto schermo ma con larghezza massima (ma anche no)
- [x] link a pagine interne dell'applicazione
- [x] piccolo indice con link a menu, nuovo grafico e visualizzazione
No screen e icone
